CREATE DATABASE SI_ISTP_AACD

USE SI_ISTP_AACD

CREATE TABLE CARRERA_PROFESIONAL (
	Cod_CarreraP INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_CarreraP VARCHAR(50) NOT NULL,
	Abrv_CarreraP CHAR(4) NOT NULL,
	Cant_Semestre INT NOT NULL,
	Cant_Vacantes_D INT NOT NULL,
	Cant_Vacantes_V INT NOT NULL
)

CREATE TABLE COLEGIO (
	Cod_Colegio INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Colegio VARCHAR(50) NOT NULL,
	Cod_Distrito INT NOT NULL
)

CREATE TABLE CURSO (
	Cod_Curso INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Curso VARCHAR(50) NOT NULL,
	Alias_Curso CHAR(4) NOT NULL,--c0001, c0002, c0003 ...
	Cant_Crd INT NOT NULL,
	Semestre VARCHAR(10) NOT NULL,
	Cod_CarreraP INT NOT NULL
)

CREATE TABLE DEPARTAMENTO (
	Cod_Dept INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Dept VARCHAR(50) NOT NULL
)

CREATE TABLE DETALLE_RD (
	Cod_Detalle_RD INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Tipo_RD VARCHAR(30) NOT NULL
)

CREATE TABLE DISTRITO (
	Cod_Distrito INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Distrito VARCHAR(50) NOT NULL,
	Cod_Provincia INT NOT NULL
)

CREATE TABLE ESTUDIANTE (
	Cod_Estudiante INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Ident_Estudiante VARCHAR(6) NOT NULL,
	Situacion_Acadm CHAR(1) NULL,
	Estado_Acadm CHAR(2) NULL
)

CREATE TABLE EXAMEN (
	Cod_Examen INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Puntaje INT NOT NULL,
	Cod_Postulante INT NOT NULL
)

CREATE TABLE HORARIO (
	Cod_Horario INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Dias VARCHAR(60) NOT NULL,
	H_Inici TIME(7) NOT NULL,
	H_Fin TIME(7) NOT NULL,
	Cod_Curso INT NOT NULL
)

CREATE TABLE MATRICULA (
	Cod_Matricula INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Obs VARCHAR(50) NULL,
	Fecha_Matricula DATE NULL,
	Cursos_Matricula VARCHAR(200) NULL, --c0001c0002c0003
	Cod_Periodo INT NOT NULL,
	Cod_Salon INT NOT NULL,
	Cod_CarreraP INT NOT NULL,
	Cod_Estudiante INT NOT NULL,
	Cod_Postulante INT NOT NULL
)

CREATE TABLE MODALIDAD (
	Cod_Modalidad INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Modalidad VARCHAR(50) NOT NULL
)

CREATE TABLE MODULO (
	Cod_Modulo INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Modulo VARCHAR(20) NOT NULL,
	Descripcion VARCHAR(60) NULL
)

CREATE TABLE PERIODO (
	Cod_Periodo INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Ini_Semestre DATE NOT NULL,
	Fin_Semestre DATE NOT NULL,
	Recuperacion DATE NOT NULL,
	Ini_Matricula DATE NOT NULL
)

CREATE TABLE PERSONA (
	Cod_Persona INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Ap_Paterno VARCHAR(60) NOT NULL,
	Ap_Materno VARCHAR(60) NOT NULL,
	Nom VARCHAR(30) NOT NULL,
	Dni CHAR(8) NOT NULL,
	Foto VARBINARY(max) NULL,
	Sexo CHAR(1) NULL,
	FechaNac DATE NULL,
	Domicilio VARCHAR(70) NULL,
	Telf_Persona VARCHAR(50) NOT NULL,
	Correo VARCHAR(40) NULL,
	Cod_Colegio INT NOT NULL,
	Cod_Distrito INT NOT NULL
)

CREATE TABLE POSTULANTE (
	Cod_Postulante INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Fecha_Inscripcion DATE NULL,
	Cod_Persona INT NOT NULL,
	Cod_Salon INT NOT NULL,
	Cod_CarreraP INT NOT NULL,
	Cod_Periodo INT NOT NULL,
	Cod_Modalidad INT NOT NULL,
	Turno CHAR(1) NOT NULL
)

CREATE TABLE PROVINCIA (
	Cod_Provincia INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Provincia VARCHAR(50) NOT NULL,
	Cod_Dept INT NOT NULL
)

CREATE TABLE RD (
	Cod_RD INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Cod_Estudiante INT NOT NULL,
	Cod_Detalle_RD INT NULL,
	RD_Doc VARBINARY(max) NULL,
	Fecha_Carga DATE NULL,
	Fecha_Emision DATE NULL
)

CREATE TABLE SALON (
	Cod_Salon INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Cant_Asientos INT NULL,
	Cod_CarreraP INT NOT NULL
)

CREATE TABLE USUARIO (
	Cod_Usuario INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nom_Usuario VARCHAR(20) NOT NULL,
	Apll_Paterno VARCHAR(20) NOT NULL,
	Apll_Materno VARCHAR(20) NOT NULL,
	Dni_Usuario VARCHAR(8) NOT NULL,
	Pass_Usuario VARCHAR(8) NOT NULL
)

CREATE TABLE USUARIO_MODULO (
	Cod_USM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Cod_Usuario INT NOT NULL,
	Cod_Modulo INT NOT NULL
)

ALTER TABLE COLEGIO  WITH CHECK ADD FOREIGN KEY(Cod_Distrito)
REFERENCES DISTRITO (Cod_Distrito)

ALTER TABLE CURSO  WITH CHECK ADD FOREIGN KEY(Cod_CarreraP)
REFERENCES CARRERA_PROFESIONAL (Cod_CarreraP)

ALTER TABLE DISTRITO  WITH CHECK ADD FOREIGN KEY(Cod_Provincia)
REFERENCES PROVINCIA (Cod_Provincia)

ALTER TABLE EXAMEN  WITH CHECK ADD FOREIGN KEY(Cod_Postulante)
REFERENCES POSTULANTE (Cod_Postulante)

ALTER TABLE HORARIO  WITH CHECK ADD FOREIGN KEY(Cod_Curso)
REFERENCES CURSO (Cod_Curso)

ALTER TABLE MATRICULA  WITH CHECK ADD FOREIGN KEY(Cod_CarreraP)
REFERENCES CARRERA_PROFESIONAL (Cod_CarreraP)

ALTER TABLE MATRICULA  WITH CHECK ADD FOREIGN KEY(Cod_Estudiante)
REFERENCES ESTUDIANTE (Cod_Estudiante)

ALTER TABLE MATRICULA  WITH CHECK ADD FOREIGN KEY(Cod_Postulante)
REFERENCES POSTULANTE (Cod_Postulante)

ALTER TABLE MATRICULA  WITH CHECK ADD FOREIGN KEY(Cod_Periodo)
REFERENCES PERIODO (Cod_Periodo)

ALTER TABLE MATRICULA  WITH CHECK ADD FOREIGN KEY(Cod_Salon)
REFERENCES SALON (Cod_Salon)

ALTER TABLE PERSONA  WITH CHECK ADD FOREIGN KEY(Cod_Colegio)
REFERENCES COLEGIO (Cod_Colegio)

ALTER TABLE PERSONA  WITH CHECK ADD FOREIGN KEY(Cod_Distrito)
REFERENCES DISTRITO (Cod_Distrito)

ALTER TABLE POSTULANTE  WITH CHECK ADD FOREIGN KEY(Cod_CarreraP)
REFERENCES CARRERA_PROFESIONAL (Cod_CarreraP)

ALTER TABLE POSTULANTE  WITH CHECK ADD FOREIGN KEY(Cod_Persona)
REFERENCES PERSONA (Cod_Persona)

ALTER TABLE POSTULANTE  WITH CHECK ADD FOREIGN KEY(Cod_Modalidad)
REFERENCES MODALIDAD (Cod_Modalidad)

ALTER TABLE POSTULANTE  WITH CHECK ADD FOREIGN KEY(Cod_Periodo)
REFERENCES PERIODO (Cod_Periodo)

ALTER TABLE POSTULANTE  WITH CHECK ADD FOREIGN KEY(Cod_Salon)
REFERENCES SALON (Cod_Salon)

ALTER TABLE PROVINCIA  WITH CHECK ADD FOREIGN KEY(Cod_Dept)
REFERENCES DEPARTAMENTO (Cod_Dept)

ALTER TABLE RD  WITH CHECK ADD FOREIGN KEY(Cod_Estudiante)
REFERENCES ESTUDIANTE (Cod_Estudiante)

ALTER TABLE RD  WITH CHECK ADD FOREIGN KEY(Cod_Detalle_RD)
REFERENCES DETALLE_RD (Cod_Detalle_RD)

ALTER TABLE SALON  WITH CHECK ADD FOREIGN KEY(Cod_CarreraP)
REFERENCES CARRERA_PROFESIONAL (Cod_CarreraP)

ALTER TABLE USUARIO_MODULO  WITH CHECK ADD FOREIGN KEY(Cod_Modulo)
REFERENCES MODULO (Cod_Modulo)

ALTER TABLE USUARIO_MODULO  WITH CHECK ADD FOREIGN KEY(Cod_Usuario)
REFERENCES USUARIO (Cod_Usuario)

