//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculaCajas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATRICULA()
        {
            this.NOTAS = new HashSet<NOTAS>();
        }
    
        public string Cod_Matricula { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> Fecha_Matricula { get; set; }
        public string Cod_Periodo { get; set; }
        public string Cod_Salon { get; set; }
        public string Cod_CarreraP { get; set; }
        public string Cod_Estudiante { get; set; }
    
        public virtual CARRERA_PROFESIONAL CARRERA_PROFESIONAL { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual PERIODO PERIODO { get; set; }
        public virtual SALON SALON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
    }
}
