//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculaCajas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMEN
    {
        public int Cod_Examen { get; set; }
        public int Puntaje { get; set; }
        public int Cod_Postulante { get; set; }
    
        public virtual POSTULANTE POSTULANTE { get; set; }
    }
}
