//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculaCajas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int Cod_Horario { get; set; }
        public string Dias { get; set; }
        public System.TimeSpan H_Inici { get; set; }
        public System.TimeSpan H_Fin { get; set; }
        public int Cod_Curso { get; set; }
    
        public virtual CURSO CURSO { get; set; }
    }
}
