//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculaCajas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        public int Cod_Matricula { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> Fecha_Matricula { get; set; }
        public string Cursos_Matricula { get; set; }
        public int Cod_Periodo { get; set; }
        public int Cod_Salon { get; set; }
        public int Cod_CarreraP { get; set; }
        public int Cod_Estudiante { get; set; }
        public int Cod_Postulante { get; set; }
    
        public virtual CARRERA_PROFESIONAL CARRERA_PROFESIONAL { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual POSTULANTE POSTULANTE { get; set; }
        public virtual PERIODO PERIODO { get; set; }
        public virtual SALON SALON { get; set; }
    }
}
