//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculaCajas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.POSTULANTE = new HashSet<POSTULANTE>();
        }
    
        public int Cod_Persona { get; set; }
        public string Ap_Paterno { get; set; }
        public string Ap_Materno { get; set; }
        public string Nom { get; set; }
        public string Dni { get; set; }
        public byte[] Foto { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Domicilio { get; set; }
        public string Telf_Persona { get; set; }
        public string Correo { get; set; }
        public int Cod_Colegio { get; set; }
        public int Cod_Distrito { get; set; }
    
        public virtual COLEGIO COLEGIO { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULANTE> POSTULANTE { get; set; }
    }
}
