//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculaCajas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_MODULO
    {
        public int Cod_USM { get; set; }
        public int Cod_Usuario { get; set; }
        public int Cod_Modulo { get; set; }
    
        public virtual MODULO MODULO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
